"""
DECLARATION DES CONSTANTES GLOBALES
"""


class MeteoCommon:

    PREVISION_AUJOURDHUI = 0
    PREVISION_J_PLUS_1: int = 1
    PREVISION_J_PLUS_2 = 2
    PREVISION_J_PLUS_3 = 3
    PREVISION_J_PLUS_4 = 4
    PREVISION_J_PLUS_5 = 5
    PREVISION_J_PLUS_6 = 6
    PREVISION_J_PLUS_7 = 7


